"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.fridayQuotes = void 0;
exports.fridayQuotes = [
    "Friday sees more smiles than any other day of the workweek!",
    "It's Friday! Time to go make stories for Monday.",
    "Fridays are the hardest in some ways: you’re so close to freedom.",
    "Make each day of the week like Friday and your life will take on new enthusiasm.",
    "Life is good, especially on a Friday.",
    "Friday is a day to finish your goals for the week. It is a day to celebrate that which you set out to accomplish at the beginning of the week.",
    "It's Friday morning mankind! Good vibe, don't frown and let the monster see you smile!",
    "The only bad Friday is Friday the 13th, and I would argue that's still better than Monday the whatever.",
    "This Friday, finish your work and be done. Look forward to the weekend and have some fun!",
    "Friday. The golden child of the weekdays. The superhero of the workweek. The welcome wagon to the weekend.",
    "Welcome to Friday. In preparation for takeoff, please ensure all negative attitudes are properly stowed. On behalf of your captain, Jack Daniels and myself, welcome aboard. I expect sunshine and good attitudes today for our trip. Enjoy the ride.",
    "Friday feels like a superhero that always arrives just in time to stop me from savagely beating one of my coworkers with a keyboard.",
    "The rhythm of the weekend, with its birth, its planned gaieties, and its announced end, followed the rhythm of life and was a substitute for it.",
    "May today be the Fridayest Friday that ever Fridayed.",
    "Friday is about hanging out with friends, having fun.",
    "Hands up if you’re ready to do something you’ll regret this weekend. Go forth! You have my blessing.",
    "Not everything will go the way you expect. Let this day remind you that you can handle more than you think you can.",
    "Youth is like a long weekend on Friday night. Middle age is like a long weekend on Monday afternoon.",
    "If my boss knew how unproductive I am on Fridays, he wouldn't want me here either.",
    "Every Friday, I like to high five myself for getting through another week on little more than caffeine, willpower, and inappropriate humor.",
    "Joy comes in sips, not gulps.",
    "Let your Friday sparkle with positivity and beat the challenges with your enthusiasm.",
    "Every single day has to be excellent. You gotta give it all you got!",
    "Today is a multiple cups of coffee kind of day.",
    "Be in love with every minute of your life – live every day like it’s your last. Happy Friday!",
    "Friday sees more smiles than any other day of the workweek!",
    "Today, be the badass girl you were too lazy to be yesterday.",
    "Happiness is a day called Friday.",
    "It’s Friday! Time to go make stories for Monday.",
    "It's finally Friday, I'm free again. I got my motor running for a wild weekend.",
    "Make a Friday a day to celebrate work well done that you can be proud of knowing that you just didn't put in time to the next paycheck.",
    "The weekends are too short for sleep!",
    "Start your Friday with a positive attitude. Believe – today is going to be a good day!",
    "Without the weekend, where would the week be?",
    "It's Friday! I can't wait to be ashamed of what I do this weekend.",
    "Life is but a moment. Love those moments each one of them.",
    "Weekends welcome warriors for social fun that starts on Friday.",
    "Friday is about hanging out with friends, having fun.",
    "Success is to wake up each morning and consciously decide that today will be the best day of your life.",
    "Cozy+smell of pancakes-alarm clock=weekend",
];
