export const fridayQuotes = [
  "Friday sees more smiles than any other day of the workweek!",
  "It's Friday! Time to go make stories for Monday.",
  "Fridays are the hardest in some ways: you’re so close to freedom.",
  "Make each day of the week like Friday and your life will take on new enthusiasm.",
  "Life is good, especially on a Friday.",
  "Friday is a day to finish your goals for the week. It is a day to celebrate that which you set out to accomplish at the beginning of the week.",
  "It's Friday morning mankind! Good vibe, don't frown and let the monster see you smile!",
  "The only bad Friday is Friday the 13th, and I would argue that's still better than Monday the whatever.",
  "This Friday, finish your work and be done. Look forward to the weekend and have some fun!",
  "Friday. The golden child of the weekdays. The superhero of the workweek. The welcome wagon to the weekend.",
  "Welcome to Friday. In preparation for takeoff, please ensure all negative attitudes are properly stowed. On behalf of your captain, Jack Daniels and myself, welcome aboard. I expect sunshine and good attitudes today for our trip. Enjoy the ride.",
  "Friday feels like a superhero that always arrives just in time to stop me from savagely beating one of my coworkers with a keyboard.",
  "The rhythm of the weekend, with its birth, its planned gaieties, and its announced end, followed the rhythm of life and was a substitute for it.",
  "May today be the Fridayest Friday that ever Fridayed.",
  "Friday is about hanging out with friends, having fun.",
  "Hands up if you’re ready to do something you’ll regret this weekend. Go forth! You have my blessing.",
  "Not everything will go the way you expect. Let this day remind you that you can handle more than you think you can.",
  "Youth is like a long weekend on Friday night. Middle age is like a long weekend on Monday afternoon.",
  "If my boss knew how unproductive I am on Fridays, he wouldn't want me here either.",
  "Every Friday, I like to high five myself for getting through another week on little more than caffeine, willpower, and inappropriate humor.",
  "Joy comes in sips, not gulps.",
  "Let your Friday sparkle with positivity and beat the challenges with your enthusiasm.",
  "Every single day has to be excellent. You gotta give it all you got!",
  "Today is a multiple cups of coffee kind of day.",
  "Be in love with every minute of your life – live every day like it’s your last. Happy Friday!",
  "Friday sees more smiles than any other day of the workweek!",
  "Today, be the badass girl you were too lazy to be yesterday.",
  "Happiness is a day called Friday.",
  "It’s Friday! Time to go make stories for Monday.",
  "It's finally Friday, I'm free again. I got my motor running for a wild weekend.",
  "Make a Friday a day to celebrate work well done that you can be proud of knowing that you just didn't put in time to the next paycheck.",
  "The weekends are too short for sleep!",
  "Start your Friday with a positive attitude. Believe – today is going to be a good day!",
  "Without the weekend, where would the week be?",
  "It's Friday! I can't wait to be ashamed of what I do this weekend.",
  "Life is but a moment. Love those moments each one of them.",
  "Weekends welcome warriors for social fun that starts on Friday.",
  "Friday is about hanging out with friends, having fun.",
  "Success is to wake up each morning and consciously decide that today will be the best day of your life.",
  "Cozy+smell of pancakes-alarm clock=weekend",
  "Friday is my second favorite F word. Food is my first!",
  "Weekends don’t count unless you spend them doing something completely pointless.",
  "Music always sounds better on Friday.",
  "Friday night is our date night. We really carve out time for each other.",
  "Life must be terrible for working people, considering they spend every Friday night celebrating a two-day break from it.",
  "Friday is like a superhero that always arrives just in time to stop me from savagely beating one of my coworkers with a keyboard.",
  "If you’ve got some news that you don’t want to get noticed, put it out Friday afternoon.",
  "Weekends are sacred for me. They’re the perfect time to relax and spend time with family and friends.",
  "Make a Friday a day to celebrate work well done that you can be proud of knowing that you just didn't put in time to the next pay check.",
  "It’s 4:58 on Friday afternoon. Do you know where your margarita is?",
  "I haven’t been so excited about Friday since last Friday.",
  "May your coffee be strong and your Friday be short.",
  "Friday is like a green light; you speed up until after work, and start to slow down once the light turns yellow.",
  "Friday. The golden child of the weekdays. The superhero of the workweek. The welcome wagon to the weekend.",
  "The first five days after the weekend are always the toughest.",
  "Friday afternoon feels like heaven.",
  "Every Friday, I feel like I deserve a new addition to my closet for all my hard work during the week.",
  "Friday is a day to finish your goals for the week. It is a day to celebrate that which you set out to accomplish at the beginning of the week.",
  "Fridays are the hardest in some ways: you’re so close to freedom.",
  "If my boss knew how unproductive I am on Fridays, he wouldn't want me here either.",
  "Friday’s a free day. A woman’s day.",
  "There's just one legitimate synonym for Friday: Boom Shakalaka.",
  "Friday is about hanging out with friends, having fun.",
  "Oh! It’s Friday again. Share the love that was missing during the week. In a worthy moment of peace and bliss.",
  "It’s Friday! Time to go make stories for Monday.",
  "Why is Monday so far away from Friday but Friday so close to Monday?",
  "There are so many beautiful reasons to love Friday.",
  "Hello, Friday. I’ve been waiting for you all week.",
  "I challenge you to let every day be a Friday. Permit yourself to be happy every day.",
  "Friday is my second favorite F word. My first is food, definitely food.",
  "I don’t work on Fridays, I make appearances.",
  "Weekends are a bit like rainbows; they look good from a distance but disappear when you get up close to them.",
  "Fridays are the beginning of my liver’s workweek.",
  "On a Friday night, I like to go out because my friends, who have been working normal hours, just want to let go after a stressful week at work.",
  "Friday is a day to finish your goals for the week. It is a day to celebrate that which you set out to accomplish at the beginning of the week.",
  "I like my coffee black and my weekends long.",
  "Dear Friday, I’m so glad we are back together. I’m sorry you had to see me with Mon-Thurs, but I swear I was thinking of you the whole time.",
  "Friday is about hanging out with friends, having fun.",
  "Let’s sit on a rooftop at 2am and talk about life.",
  "Spend some time this weekend on home improvement; improve your attitude toward your family.",
];
